import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navigation/navbar";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import { headers } from "next/headers";
import { WagmiContextProvider } from "@/context";
import { Web3StatusProvider } from "./components/web3/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YieldNest",
  description: "Generated by YieldNest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiContextProvider initialState={initialState}>
          <Web3StatusProvider>
          <Navbar />
          <div className="container mx-auto">{children}</div>
          </Web3StatusProvider>
        </WagmiContextProvider>
      </body>
    </html>
  );
}
